export const gbpLocation = {
  storeName: "Spirit Corner Cannabis",
  domain: "spiritcornercannabis.com",
  city: "Ottawa",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-ottawa",
  address: "251 Dalhousie St, Ottawa, ON K1N 1E7",
  streetAddress: "251 Dalhousie St",
  postalCode: "K1N 1E7",
  phone: "(343) 308-8998",
  phoneIntl: "+13433088998",
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Accessories",
  ],
  latitude: "45.4310488",
  longitude: "-75.6927362",
  hours: ["Open 24 Hours"],
  seoTitle: "24 Hour Ottawa Dispensary Near ByWard Market | Spirit Corner Cannabis",
  metaDescription:
    "Spirit Corner Cannabis is open 24 hours at 251 Dalhousie St near ByWard Market in downtown Ottawa. Adults 19+ can compare listed flower and other product categories.",
};
