// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Spirit Corner Cannabis",
  domain: "spiritcornercannabis.com",
  city: "Ottawa",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-ottawa",
  address: "251 Dalhousie St, Ottawa, ON K1N 1E7",
  streetAddress: "251 Dalhousie St",
  postalCode: "K1N 1E7",
  phone: "(613) 612-2107",
  phoneIntl: "+16136122107",
  neighborhood: "Ottawa",
  nearbyAreas: ["ByWard Market", "Lowertown", "Centretown", "Sandy Hill", "Ottawa", "Dalhousie Street", "Rideau River", "OC Transpo"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.app.goo.gl/yVDY1PZ8qSwAjQ6s6",
  mapEmbedUrl: "https://maps.google.com/maps?q=Spirit%20Corner%20Cannabis%20251%20Dalhousie%20St%2C%20Ottawa%2C%20ON%20K1N%201E7&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "45.4292",
  longitude: "-75.6928",
  hours: ["Open 24 Hours"],
  seoTitle: "Spirit Corner Cannabis | Weed Dispensary in Ottawa",
  metaDescription: "Spirit Corner Cannabis is a local weed dispensary in Ottawa offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["ByWard Market", "Lowertown", "Centretown"],
  introVariant: "If you are searching for a reliable weed dispensary in Ottawa, Spirit Corner Cannabis at 251 Dalhousie St is your go-to destination. We serve adults 19+ with a vast selection of weed products including cannabis flower, pre-rolls, edibles, THC vapes, shatter, and CBD oils. Serving customers near Ottawa and surrounding communities like Lowertown, our cannabis store and weed shop is focused on quality and convenience.",
  neighborhoodDescription: "Located in the vibrant Ottawa district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Dalhousie Street",
  transitNote: "Accessible by OC Transpo routes serving nearby Ottawa neighborhoods.",
  sectionTitle: "Serving Customers Near ByWard Market and Ottawa"
};
